version: '3.8'

services:

  eureka-server:
    image: harshitha2802/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - lenscart-net
    environment:
      - spring.profiles.active=docker

  lenses-service:
    image: lenses-service:latest
    container_name: lenses-service
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - lenscart-net
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - server.port=8082
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/lenses?createDatabaseIfNotExist=true
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}

  frames-service:
    image: frames-service:latest
    container_name: frames-service
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - lenscart-net
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - server.port=8083
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/frames?createDatabaseIfNotExist=true
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}

  glass-service:
    image: glass-service:latest
    container_name: glass-service
    ports:
      - "8084:8084"
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - lenscart-net
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - server.port=8084
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/glass_data?createDatabaseIfNotExist=true
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}

  sunglasses-service:
    image: sunglasses-service:latest
    container_name: sunglasses-service
    ports:
      - "8086:8086"
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - lenscart-net
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - server.port=8086
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/sunglass_db?createDatabaseIfNotExist=true
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}

  cart-service:
    image: cart-service:latest
    container_name: cart-service
    ports:
      - "8087:8087"
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - lenscart-net
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - server.port=8087
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/cartdb?createDatabaseIfNotExist=true
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}

  customer-admin-service:
    image: customer-admin-service:latest
    container_name: customer-admin-service
    ports:
      - "8085:8085"
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - lenscart-net
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - server.port=8085
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/customer_admin_db?createDatabaseIfNotExist=true
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}

  product-service:
    image: product-service:latest
    container_name: product-service
    ports:
      - "8089:8089"
    depends_on:
      - eureka-server
    networks:
      - lenscart-net
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - server.port=8089

  orders-service:
    image: orders-service:latest
    container_name: orders-service
    ports:
      - "8088:8088"
    depends_on:
      - eureka-server
      - mysql-db
    networks:
      - lenscart-net
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - server.port=8088
      - spring.datasource.url=jdbc:mysql://mysql-db:3306/orders_db?createDatabaseIfNotExist=true
      - spring.datasource.username=${DB_USERNAME}
      - spring.datasource.password=${DB_PASSWORD}

  frontend:
    build: ./frontend
    container_name: lenscart-frontend
    ports:
      - "4200:80"
    depends_on:
      - eureka-server
      - lenses-service
      - frames-service
      - glass-service
      - customer-admin-service
      - sunglasses-service
      - cart-service
      - orders-service
      - product-service
    networks:
      - lenscart-net

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    networks:
      - lenscart-net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

networks:
  lenscart-net:
    driver: bridge

volumes:
  mysql-data: