name: Build & Push Product Service

on:
  push:
    branches:
      - master
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Product Service JAR
        run: |
          cd backend/product-sevice
          chmod +x mvnw
          ./mvnw clean package -DskipTests
          ls -l target/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build & Push Product Service Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./backend/product-sevice
          file: ./backend/product-sevice/Dockerfile
          push: true
          tags: harshitha2802/product-service:latest